version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: pip
    directory: /edge-client
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: npm
    directory: /frontend-admin
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /frontend-admin
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /edge-client
    schedule:
      interval: weekly
    target-branch: master

  - package-ecosystem: docker
    directory: /nginx
    schedule:
      interval: weekly
    target-branch: master
